Repository MANISH-CHOUHAN/hacktoberfest, pull requests merged in 2020-10, with the labels that each got.

#2 Make code readable by adding comments
  PALINDROME
Labels: hacktoberfest-accepted

#1 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#3 Made Code Commented
  PALINDROME
Labels: hacktoberfest-accepted

#4 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#5 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#9 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#8 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#7 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#6 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#11 Update Armstrong no
  Armstrong no
  Factorial
Labels: hacktoberfest-accepted

#13 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#12 Update Factorial // MORE USEFUL
  Factorial
  Prime no
Labels: hacktoberfest-accepted

#14 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#15 Update Star pattern
  Star pattern
Labels: hacktoberfest-accepted

#16 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#17 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#18 Update Star pattern
  Star pattern
Labels: hacktoberfest-accepted

#19 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#20 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#21 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#22 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#23 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#24 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#25 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#26 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#27 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#28 Update PALINDROME
  PALINDROME
Labels: good first issue, hacktoberfest-accepted

#34 Update Star pattern
  Star pattern
Labels: hacktoberfest-accepted

#33 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#32 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#31 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#30 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#35 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#39 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#38 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#37 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#36 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#44 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#43 Update Star pattern
  Star pattern
Labels: hacktoberfest-accepted

#42 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#41 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#40 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#45 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#49 Update Star pattern
  Star pattern
Labels: hacktoberfest-accepted

#48 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#47 Update Fibonnaci series
  Fibonnaci series
Labels: enhancement, hacktoberfest-accepted

#46 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#54 Update Star pattern
  Star pattern
Labels: good first issue, hacktoberfest-accepted

#53 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#52 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#51 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#50 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#55 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#59 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#58 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#57 Update Prime no
  Prime no
Labels: hacktoberfest-accepted

#56 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#61 Update Armstrong no
  Armstrong no
Labels: hacktoberfest-accepted

#62 Update Factorial
  Factorial
Labels: hacktoberfest-accepted

#63 Update Fibonnaci series
  Fibonnaci series
Labels: hacktoberfest-accepted

#64 Update PALINDROME
  PALINDROME
Labels: hacktoberfest-accepted

#65 Update Prime no
  Prime no
Labels: enhancement, good first issue, hacktoberfest-accepted
